<a href="https://colab.research.google.com/github/Nivedh-prog/aiml-assignments/blob/main/Copy_of_Untitled35.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Shape & Type Check: Print the shape and data type of the `data` array. Then

---

convert it to float.


In [1]:
import numpy as np
data = np.array([
 [25, 78, 45, 62],
 [30, 85, 60, 74],
 [35, 90, 72, 80],
 [28, 70, 50, 65],
 [40, 88, 69, 85]
])

In [2]:
print(data.shape)
print(data.dtype)

(5, 4)
int64


In [3]:
flt = data.astype(float)

In [4]:
flt

array([[25., 78., 45., 62.],
       [30., 85., 60., 74.],
       [35., 90., 72., 80.],
       [28., 70., 50., 65.],
       [40., 88., 69., 85.]])

2. Score Filtering: Find the rows where both Test Score 1 > 80 and Final Evaluation Score > 75.


In [5]:
rows = data[(data[:, 1] > 80) & (data[:, 3] > 75)]
#(if both)

print(rows)


[[35 90 72 80]
 [40 88 69 85]]


In [6]:
data

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

3. Normalization: Normalize all columns except Age to the range [0, 1].


In [7]:
new_d = data.copy()
for i in range(1, 4):
    min_value = data[:,i].min()
    max_value = data[:,i].max()
    new_d[:,i] = (data[:,i]-min_value)/(max_value-min_value)
new_d

array([[25,  0,  0,  0],
       [30,  0,  0,  0],
       [35,  1,  1,  0],
       [28,  0,  0,  0],
       [40,  0,  0,  1]])

In [8]:
data

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

4. Conditional Replacement: Replace all Final Evaluation Scores less than 70 with the average of all Final
Evaluation Scores.

In [9]:
xy = data[:,-1]
xy

array([62, 74, 80, 65, 85])

In [10]:
mask = xy<70

In [11]:
mask

array([ True, False, False,  True, False])

In [12]:
xy[mask] = xy[mask]*xy.mean()

In [13]:
xy

array([4538,   74,   80, 4758,   85])

5. Mean Scores: Compute the mean score per column and the mean score per person (row).


In [14]:
mean_column = data.mean(axis=0)
mean_row =  data.mean(axis=1)

In [15]:
mean_column

array([  31.6,   82.2,   59.2, 1907. ])

In [16]:
mean_row

array([1171.5 ,   62.25,   69.25, 1226.5 ,   70.5 ])

6. Sorting by Test Score 2: Sort the entire array based on Test Score 2 (Column 2) in descending order.


In [17]:
data = np.array([
 [25, 78, 45, 62],
 [30, 85, 60, 74],
 [35, 90, 72, 80],
 [28, 70, 50, 65],
 [40, 88, 69, 85]
])


In [18]:
flt = data[:,2]

In [19]:
srt = data.copy()
srt_new = srt[srt[:,2].argsort()[::-1]]

In [20]:
srt_new

array([[35, 90, 72, 80],
       [40, 88, 69, 85],
       [30, 85, 60, 74],
       [28, 70, 50, 65],
       [25, 78, 45, 62]])

7. Rank Assignment: Assign ranks (1 being highest) to all people based on their Final Evaluation Score and
append it as a new column.

In [21]:
data

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

In [22]:
rank = data.copy()
rank

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

In [23]:
rank_new = rank[:,-1]
rank_new

array([62, 74, 80, 65, 85])

In [24]:
sorted = rank_new.argsort()[::-1]+1
sorted_new=sorted.reshape(-1, 1)

In [25]:
combined = np.hstack((rank, sorted_new))
combined

array([[25, 78, 45, 62,  5],
       [30, 85, 60, 74,  3],
       [35, 90, 72, 80,  2],
       [28, 70, 50, 65,  4],
       [40, 88, 69, 85,  1]])

8. Detect Outliers: Find rows where any score is more than 1.5 standard deviations from the column mean.
Return those rows.

In [26]:
means = data.mean(axis=0)
stds = data.std(axis=0)
print(means)
print(stds*1.5)
outliers = []
for row in data:
    poss = np.abs(row-means)
    if np.any(poss > 1.5*stds):
        outliers.append(row)

outliers = np.array(outliers)
print(outliers)

[31.6 82.2 59.2 73.2]
[ 7.97119815 10.99818167 15.68629975 13.05603309]
[[28 70 50 65]
 [40 88 69 85]]


In [27]:
data

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

9. Weighted Total Score: Calculate a weighted total score using:
 - 30% from Test Score 1
 - 30% from Test Score 2
 - 40% from Final Evaluation Score
 Return a 1D array of the scores

In [28]:
ws = 0.3*data[:,1] + 0.3*data[:,2] + 0.4*data[:,3]

In [29]:
ws

array([61.7, 73.1, 80.6, 62. , 81.1])

In [30]:
data

array([[25, 78, 45, 62],
       [30, 85, 60, 74],
       [35, 90, 72, 80],
       [28, 70, 50, 65],
       [40, 88, 69, 85]])

[link text](https://)10. Row-wise Max Column Index: For each person (row), find the index of the column that contains their
highest score.

In [31]:
max_indices = data.argmax(axis=1)
print(max_indices.reshape(-1,1))

[[1]
 [1]
 [1]
 [1]
 [1]]
